- hosts: prodservers
  become: yes
  gather_facts: True

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure apt dependencies are present
      apt:
        name:
          - python3-dev
          - python3-pip
          - python3-virtualenv
          - virtualenv
          - git
        state: present
      when: ansible_os_family == "Debian"

    - name: Add the user running webapp
      user:
        name: "flask"
        state: present
        append: yes # important pour ne pas supprimer les groupes d'un utilisateur existant
        groups:
        - "www-data"
      when: ansible_os_family == "Debian"

    - name: Git clone/update python hello webapp in user home
      git:
        repo: "https://github.com/e-lie/flask_hello_ansible.git"
        dest: /home/flask/hello
        version: "master"
        clone: yes
        update: no
      when: ansible_os_family == "Debian"
    
    - name: Install python dependencies for the webapp in a virtualenv
      pip:
        requirements: /home/flask/hello/requirements.txt
        virtualenv: /home/flask/hello/venv
        virtualenv_python: python3
      when: ansible_os_family == "Debian"
    
    - name: Change permissions of app directory recursively
      file:
        path: /home/flask/hello
        state: directory
        owner: "flask"
        group: www-data
        recurse: true
      when: ansible_os_family == "Debian"
