---
- name: My first play
  hosts: prod
  gather_facts: True
  become: true
  #become_method: sudo
  #become_user: root
  vars:
    test: True
  vars_files: userlist.yaml
  pre_tasks:
    - name: "PRE-TASK 1: collect facts"
      setup:
  tasks:
    - name: "TASK 1: Ping my hosts"
      ping:
      register: output

    - name: "TASK 2: print variable output"
      debug:
        var: output
      when: test == True

    - name: "TASK 3: print hostname"
      debug:
        msg: "{{ ansible_hostname }} is {{ output.ping }}ing"


    # - name: install redis on Debian based distros
    #   apt:
    #    name: redis-server
    #    state: present
    #    update_cache: true
    #   when: ansible_os_family == 'Debian'

    # - name: Remove useless packages from the cache
    #   apt:
    #     autoclean: yes

    # - name: Remove dependencies that are no longer required
    #   apt:
    #     autoremove: yes

    # - name: Create group
    #   group:
    #     name: "groupe1"
    #     state: present

    # - name: Create Users Task
    #   user:
    #     name: "{{ item }}"
    #     state: present
    #     password: "{{ default_user_password | password_hash('sha512','A512') }}"
    #     shell: /bin/bash
    #     group: "{{ admin_group }}"
    #   loop:
    #     - Rajini
    #     - Kamal
  post_tasks:
    - name: "POST-TASK 1: Error handeling"
      command: /bin/false
      register: output
      ignore_errors: True

    - name: "POST-TASK 2: Error handeling and idempotency"
      command: /bin/false
      register: output
      ignore_errors: True
      changed_when: output.rc == 0

    - name: "POST-TASK 3: Idempotency with True"
      command: /bin/true
      register: output
      changed_when: output.rc == 1